### ISSUE TITLE
Secondary TODO list

### ISSUE THREAD

**Issue by edomora97** [e-register/e-register#3]
These are points to cover when #1 is finished:
- [ ] Implement the controllers and the views
    - [ ] Login
    - [ ] Homepage
    - [ ] User page
    - [ ] Class page
    - [ ] Class/Evaluations page
    - [ ] Class/Presences page
    - [ ] Class/Notes page
    - [ ] User/Notes page
    - [ ] Class/Events page
    - [ ] Class/Signs page
- [ ] Implement the support for `parents` and `admins`
    - [ ] Admin levels: superuser, class coordinator, secretary
- [ ] Improve views and user experience using ajax
    - [ ] Remote forms
    - [ ] Client side framework? Angular/Ember/Backbone?
- [ ] Implement an Admin Interface
    - [ ] Class coordinator interface
    - [ ] Global administration interface
- [ ] Implement an Data Exporter
    - [ ] PDF reports
    - [ ] CSV/EXCEL statistics exporter
